### PR TITLE
Expose suite-specific KDF and AEAD interface.

### LINKED ISSUE #96: Expose suite-specific KDF and AEAD interfaces
Some protocols that build on top of HPKE, such as [Oblivious HTTP](https://ietf-wg-ohai.github.io/oblivious-http/draft-ietf-ohai-ohttp.html), use the KDF and AEAD interfaces associated with a HPKE suite for various things. In the specific case of OHTTP, the KDF and AEAD interfaces are used to [encapsulate HTTP responses](https://ietf-wg-ohai.github.io/oblivious-http/draft-ietf-ohai-ohttp.html#name-encapsulation-of-responses) (pseudocode copied from the draft):

```
secret = context.Export("message/bhttp response", Nk)
response_nonce = random(max(Nn, Nk))
salt = concat(enc, response_nonce)
prk = Extract(salt, secret)
aead_key = Expand(prk, "key", Nk)
aead_nonce = Expand(prk, "nonce", Nn)
ct = Seal(aead_key, aead_nonce, "", response)
enc_response = concat(response_nonce, ct)
```

I don't see an obvious was to get access to these interfaces through the things that hpke-js exposes. One could certainly reimplement the KDF and AEAD interfaces on top of WebCrypto, but it seems a lot less error prone if this library allowed the caller to just use the already-implemented functions directly. 

@dajiaji, what do you think about exposing these? For context, I'm trying to implement a Javascript version of OHTTP, and this is the last bit that's required.

### PR DESCRIPTION
**Pull request by dajiaji**
Expose suite-specific KDF and AEAD interfaces for some HPKE applications (e.g., Oblivious HTTP).
Specifically, add following functions to hpke.CipherSuite class.
- kdfContext()
- createAeadKey()

Close #96

### CODE REVIEW

**Comment by dajiaji** [comment]
@chris-wood I've implemented what you requested on a trial basis.

```
secret = context.Export("message/bhttp response", Nk)
response_nonce = random(max(Nn, Nk))
salt = concat(enc, response_nonce)
prk = Extract(salt, secret)
aead_key = Expand(prk, "key", Nk)
aead_nonce = Expand(prk, "nonce", Nn)
ct = Seal(aead_key, aead_nonce, "", response)
enc_response = concat(response_nonce, ct)
```

A sample implementation corresponding to the above OHTTP pseudo code is shown below.
Can you confirm that the design is what you intended?

https://github.com/dajiaji/hpke-js/blob/expose-kdf-aead/test/cipherSuite.test.ts#L1223-L1246

**Comment by chris-wood** [comment]
@dajiaji this looks great and is exactly what I was looking for! My only suggestion would be to encapsulate `Nn` and `Nk` behind functions on the ciphersuite. That is, instead of [hard coding them](https://github.com/dajiaji/hpke-js/blob/expose-kdf-aead/test/cipherSuite.test.ts#L1212-L1213), maybe we could add a function `aeadKeySize` and `aeadNonceSize`, respectively?

**Comment by dajiaji** [comment]
@chris-wood By the way, the following part is problematic for Web Cryptography API.

```
salt = concat(enc, response_nonce)
prk = Extract(salt, secret)
```

In case of HKDF-SHA256, the length of the salt (=HMAC key) must be 32 bytes for the HMAC SHA256 processing on Web Cryptography API. If it is essential to use salt values larger than 32 bytes, then Extract() must be reimplemented in a way that does not use the Web Cryptography API.

**Comment by chris-wood** [comment]
That's not good... the salt will almost always be more than 32 bytes since response.enc is usually at least 32 bytes long. How challenging would it be to re-implement Extract without using the WebCrypto APIs?

**Comment by dajiaji** [comment]
@chris-wood 

I've just added aeadKeySize and aeadNonceSize and updated the sample program.

> That's not good... the salt will almost always be more than 32 bytes since response.enc is usually at least 32 bytes long. How challenging would it be to re-implement Extract without using the WebCrypto APIs?

It's just an HMAC-SHA signature process, so it's not that difficult, but give me one more day :-)

**Review by chris-wood — APPROVED** [review]
🎉 looks great! I don't know if the Workers tests are expected to fail (the reason looks unrelated to this change), so I'd say this is good to go. Thanks for doing the work. =)

**Comment by dajiaji** [comment]
@chris-wood I've released v0.14.0 that includes this change. For HKDF-SHA256 and HKDF-SHA512, larger salt values than Nh are supported.

Note that you can use only Nh-length salt for HKDF-SHA384 at this time. We hope to make the time to support HKDF-SHA384 eventually.

**Pull request merged**
